kind = "web"
previewPath = "/"
title = "ServRedi App"
version = "1.0.0"
id = "artifacts/servredi"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19383

[services.development]
run = "pnpm --filter @workspace/servredi run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/servredi", "run", "build" ]
publicDir = "artifacts/servredi/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19383"
BASE_PATH = "/"
